# Server Properties
kraken:
    server:
        core:
            concurrent-crack-requests: 1
            concurrent-candidate-value-lists: 1
            job-retry: 3
            job-size: 2000000
        gearman-server-port: 4730

spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        #url: jdbc:h2:file:./${kraken.tmp-folder-base}/data
        url: jdbc:h2:file:~/test
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect