# Base Application Properties

kraken:
    tmp-folder:
        base: kraken-temp-folder

server:
    port: 8090

spring:
    profiles:
        active: server,worker
    datasource:
        url: jdbc:h2:file:./${kraken.tmp-folder-base}/data
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect